from __future__ import annotations

from .contracts import DocumentMetadata


SOURCE_CORPUS: tuple[tuple[DocumentMetadata, str, str], ...] = (
    (DocumentMetadata(document_id="acme-10k-2022", company="Acme Systems", filing_type="10-K", filing_date="2022-12-31", section="Liquidity", source_url="https://example.invalid/acme/2022"), "liquidity", "Cash and cash equivalents were $2.1 billion, while $3.4 billion of debt matures within twelve months."),
    (DocumentMetadata(document_id="acme-10k-2023", company="Acme Systems", filing_type="10-K", filing_date="2023-12-31", section="Liquidity", source_url="https://example.invalid/acme/2023"), "liquidity", "Operating cash flow may not be sufficient to fund capital expenditures and scheduled debt repayments."),
    (DocumentMetadata(document_id="acme-10q-2024q1", company="Acme Systems", filing_type="10-Q", filing_date="2024-03-31", section="Debt", source_url="https://example.invalid/acme/2024q1"), "leverage", "Our ability to service debt depends on continued operating cash flow and access to capital markets."),
    (DocumentMetadata(document_id="acme-10q-2024q2", company="Acme Systems", filing_type="10-Q", filing_date="2024-06-30", section="Debt", source_url="https://example.invalid/acme/2024q2"), "leverage", "A one percentage point increase in interest rates would increase annual interest expense by approximately $42 million."),
    (DocumentMetadata(document_id="nova-10k-2022", company="Nova Retail", filing_type="10-K", filing_date="2022-12-31", section="Customers", source_url="https://example.invalid/nova/2022"), "customer_concentration", "One customer represented 18% of consolidated revenue in the reporting period."),
    (DocumentMetadata(document_id="nova-10k-2023", company="Nova Retail", filing_type="10-K", filing_date="2023-12-31", section="Customers", source_url="https://example.invalid/nova/2023"), "customer_concentration", "The loss of any of our three largest customers could materially reduce net sales."),
    (DocumentMetadata(document_id="orbit-10k-2022", company="Orbit Devices", filing_type="10-K", filing_date="2022-12-31", section="Competition", source_url="https://example.invalid/orbit/2022"), "competition", "We compete with larger companies that may have greater resources, distribution, and pricing flexibility."),
    (DocumentMetadata(document_id="orbit-10k-2023", company="Orbit Devices", filing_type="10-K", filing_date="2023-12-31", section="Competition", source_url="https://example.invalid/orbit/2023"), "competition", "Aggressive pricing by competitors could reduce our margins and market share."),
    (DocumentMetadata(document_id="green-10k-2022", company="GreenGrid", filing_type="10-K", filing_date="2022-12-31", section="Regulation", source_url="https://example.invalid/greengrid/2022"), "regulation", "Changes in privacy, artificial intelligence, and cross-border data regulations may increase compliance costs."),
    (DocumentMetadata(document_id="green-10k-2023", company="GreenGrid", filing_type="10-K", filing_date="2023-12-31", section="Regulation", source_url="https://example.invalid/greengrid/2023"), "regulation", "New environmental reporting requirements could require material changes to our operating processes."),
    (DocumentMetadata(document_id="secure-10k-2022", company="SecureCloud", filing_type="10-K", filing_date="2022-12-31", section="Cybersecurity", source_url="https://example.invalid/securecloud/2022"), "cybersecurity", "A security incident could disrupt operations, expose confidential information, and result in litigation."),
    (DocumentMetadata(document_id="secure-10k-2023", company="SecureCloud", filing_type="10-K", filing_date="2023-12-31", section="Cybersecurity", source_url="https://example.invalid/securecloud/2023"), "cybersecurity", "We have experienced phishing attempts and cannot guarantee that our controls will prevent every breach."),
    (DocumentMetadata(document_id="micro-10k-2022", company="MicroFab", filing_type="10-K", filing_date="2022-12-31", section="Supply Chain", source_url="https://example.invalid/microfab/2022"), "supply_chain", "Limited availability of advanced components could delay deliveries and constrain production."),
    (DocumentMetadata(document_id="micro-10k-2023", company="MicroFab", filing_type="10-K", filing_date="2023-12-31", section="Supply Chain", source_url="https://example.invalid/microfab/2023"), "supply_chain", "A disruption at a single qualified supplier could interrupt manufacturing for several quarters."),
    (DocumentMetadata(document_id="atlas-10q-2023q1", company="Atlas Health", filing_type="10-Q", filing_date="2023-03-31", section="Liquidity", source_url="https://example.invalid/atlas/2023q1"), "liquidity", "We held $780 million in cash and had $1.2 billion of committed revolving capacity at quarter end."),
    (DocumentMetadata(document_id="atlas-10q-2023q2", company="Atlas Health", filing_type="10-Q", filing_date="2023-06-30", section="Competition", source_url="https://example.invalid/atlas/2023q2"), "competition", "Several new entrants are offering lower-cost alternatives in our core market."),
    (DocumentMetadata(document_id="vertex-10k-2023", company="Vertex Media", filing_type="10-K", filing_date="2023-12-31", section="Customers", source_url="https://example.invalid/vertex/2023"), "customer_concentration", "Our ten largest advertisers generated 46% of total advertising revenue."),
    (DocumentMetadata(document_id="vertex-10q-2024q1", company="Vertex Media", filing_type="10-Q", filing_date="2024-03-31", section="Regulation", source_url="https://example.invalid/vertex/2024q1"), "regulation", "Platform moderation rules may change the content we can monetize."),
    (DocumentMetadata(document_id="quanta-10k-2023", company="Quanta Labs", filing_type="10-K", filing_date="2023-12-31", section="Risk Factors", source_url="https://example.invalid/quanta/2023"), "insufficient_evidence", "The company describes its mission and values but provides no quantified risk evidence in this excerpt."),
    (DocumentMetadata(document_id="quanta-10q-2024q1", company="Quanta Labs", filing_type="10-Q", filing_date="2024-03-31", section="Risk Factors", source_url="https://example.invalid/quanta/2024q1"), "insufficient_evidence", "This excerpt discusses product objectives and does not identify a specific financial or operational exposure."),
)
