from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def verify_merged_checkpoint(path: str | Path) -> dict[str, Any]:
    checkpoint = Path(path)
    files = sorted(item.name for item in checkpoint.iterdir()) if checkpoint.exists() else []
    has_config = "config.json" in files
    has_tokenizer = any(name.startswith("tokenizer") for name in files)
    has_weights = any(name.endswith((".safetensors", ".bin")) for name in files)
    return {"path": str(checkpoint), "exists": checkpoint.exists(), "files": files, "config_present": has_config, "tokenizer_present": has_tokenizer, "weights_present": has_weights, "reload_verified": False, "ready_to_publish": has_config and has_tokenizer and has_weights}


def write_merged_manifest(output: str | Path, checkpoint: str | Path, *, base_model: str = "Qwen/Qwen2.5-1.5B-Instruct") -> Path:
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = {"artifact": "merged_student_model", "status": "not_run", "base_model": base_model, "checkpoint": verify_merged_checkpoint(checkpoint), "license": "Apache-2.0", "upload_status": "not_uploaded"}
    destination.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return destination


def render_model_card(output: str | Path, metrics: dict[str, Any] | None = None) -> Path:
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    metric_text = json.dumps(metrics or {"status": "not_run"}, indent=2)
    content = """# FinSight filing risk extractor\n\nBase model: `Qwen/Qwen2.5-1.5B-Instruct`\n\nThis card is generated by the Task 2 pipeline. It must be updated after a real Colab QLoRA run with the exact revision, dataset hash, training configuration, evaluation metrics, and limitations.\n\n## Evidence policy\n\nThe extractor may quote only text in the supplied filing excerpt and must preserve the document reference. It abstains when the excerpt does not support a risk.\n\n## Evaluation\n\n```json\n""" + metric_text + "\n```\n\n## Publication\n\nUpload is intentionally separate from training. Review the merged checkpoint and remove private traces before publishing.\n"
    destination.write_text(content, encoding="utf-8")
    return destination


def publish_merged_model(checkpoint: str | Path, repo_id: str, token: str | None = None, private: bool = False) -> dict[str, Any]:
    """Upload only an already verified merged checkpoint when the caller opts in."""
    verification = verify_merged_checkpoint(checkpoint)
    if not verification["ready_to_publish"]:
        raise RuntimeError("Merged checkpoint is incomplete; verify config, tokenizer, and weights first")
    try:
        from huggingface_hub import HfApi
    except ImportError as exc:
        raise RuntimeError("Install huggingface_hub before publishing") from exc
    api = HfApi(token=token)
    result = api.upload_folder(repo_id=repo_id, folder_path=str(checkpoint), repo_type="model", private=private)
    return {"repo_id": repo_id, "private": private, "url": str(result), "status": "uploaded"}
