import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const DisclaimerBanner: React.FC = () => {
  return (
    <div
      id="regulatory-disclaimer-banner"
      style={{
        background: 'rgba(245, 158, 11, 0.08)',
        border: '1px solid rgba(245, 158, 11, 0.25)',
        borderRadius: 'var(--radius-md)',
        padding: '10px 16px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        fontSize: '12px',
        color: '#fcd34d',
        marginBottom: '20px'
      }}
    >
      <ShieldAlert size={18} style={{ flexShrink: 0, color: 'var(--accent-amber)' }} />
      <div>
        <strong>Regulatory Notice:</strong> FinSight AI is a research and demonstration platform. Information generated by the system does not constitute financial advice and should not be considered a recommendation to buy or sell securities. No live money trading is executed.
      </div>
    </div>
  );
};
