"""
FinSight AI - Workflow API Endpoints
Manages stateful LangGraph research workflows, SSE event streaming, and resumption.
"""

from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from backend.app.orchestration.graph import workflow_engine
from backend.app.orchestration.state import WorkflowState
from backend.app.core.security import get_current_user, TokenPayload

router = APIRouter()

class CreateWorkflowRequest(BaseModel):
    ticker: str = "AAPL"

class ResumeWorkflowRequest(BaseModel):
    decision: str = "APPROVE"
    reason: Optional[str] = None
    reviewed_by: Optional[str] = None

@router.post("/research", response_model=WorkflowState)
async def start_research_workflow(
    req: CreateWorkflowRequest,
    user: TokenPayload = Depends(get_current_user)
):
    """Start an autonomous LangGraph investment research workflow for a given ticker."""
    try:
        state = await workflow_engine.start_workflow(ticker=req.ticker, owner_id=user.sub or "demo_analyst")
        return state
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{workflow_id}", response_model=WorkflowState)
async def get_workflow_state(workflow_id: str, user: TokenPayload = Depends(get_current_user)):
    """Retrieve full execution state and history for an active or completed workflow."""
    state = workflow_engine.get_workflow(workflow_id)
    if not state:
        raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found.")
    _check_owner(state, user)
    return state

@router.get("/{workflow_id}/events")
async def stream_workflow_events(workflow_id: str, user: TokenPayload = Depends(get_current_user)):
    """Stream real-time Server-Sent Events (SSE) for workflow progression."""
    state = workflow_engine.get_workflow(workflow_id)
    if not state:
        raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found.")
    _check_owner(state, user)
    return StreamingResponse(
        workflow_engine.stream_workflow_events(workflow_id),
        media_type="text/event-stream"
    )

@router.post("/{workflow_id}/resume", response_model=WorkflowState)
async def resume_workflow(
    workflow_id: str,
    req: ResumeWorkflowRequest,
    user: TokenPayload = Depends(get_current_user)
):
    """Resume an interrupted workflow after human operator approval."""
    reviewer = user.sub or "demo_analyst"
    state = workflow_engine.get_workflow(workflow_id)
    if not state:
        raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found.")
    _check_owner(state, user)
    try:
        state = await workflow_engine.resume_workflow(
            workflow_id=workflow_id,
            reviewed_by=reviewer,
            decision=req.decision,
            reason=req.reason
        )
        return state
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/{workflow_id}/cancel", response_model=WorkflowState)
async def cancel_workflow(workflow_id: str, user: TokenPayload = Depends(get_current_user)):
    """Cancel a running or pending workflow."""
    try:
        state = workflow_engine.get_workflow(workflow_id)
        if not state:
            raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found.")
        _check_owner(state, user)
        return workflow_engine.cancel_workflow(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

@router.get("/{workflow_id}/artifacts")
async def get_workflow_artifacts(workflow_id: str, user: TokenPayload = Depends(get_current_user)) -> Dict[str, Any]:
    """Retrieve all structured Pydantic artifacts generated by the workflow."""
    state = workflow_engine.get_workflow(workflow_id)
    if not state:
        raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found.")
    _check_owner(state, user)
    return {
        "workflow_id": state.workflow_id,
        "ticker": state.ticker,
        "status": state.status,
        "research_output": state.research_output,
        "strategy_spec": state.strategy_spec,
        "candidate_code": state.candidate_code,
        "qa_results": state.qa_results,
        "backtest_result": state.backtest_result,
        "approval_record": state.approval_record,
        "shadow_result": state.shadow_result,
        "recommendation": state.recommendation
    }


def _check_owner(state: WorkflowState, user: TokenPayload) -> None:
    if state.owner_id != user.sub and user.role not in {"admin", "supervisor"}:
        raise HTTPException(status_code=404, detail="Workflow not found")
