from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from contextlib import asynccontextmanager
import time
import uuid

from backend.app.config import settings
from backend.app.core.logging import logger
from backend.app.database.session import init_db

# Routers
from backend.app.api.v1.auth import router as auth_router
from backend.app.api.v1.stocks import router as stocks_router
from backend.app.api.v1.analytics import router as analytics_router
from backend.app.api.v1.sentiment import router as sentiment_router
from backend.app.api.v1.rag import router as rag_router
from backend.app.api.v1.documents import router as documents_router
from backend.app.api.v1.agents import router as agents_router
from backend.app.api.v1.chat import router as chat_router
from backend.app.api.v1.portfolio import router as portfolio_router
from backend.app.api.v1.ml import router as ml_router
from backend.app.api.v1.multimodal import router as multimodal_router
from backend.app.api.v1.voice import router as voice_router
from backend.app.api.v1.showcase import router as showcase_router
from backend.app.api.v1.workflows import router as workflows_router
from backend.app.api.v1.approvals import router as approvals_router
from backend.app.api.v1.strategies import router as strategies_router
from backend.app.api.v1.system import router as system_router

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info(f"Starting {settings.APP_NAME} in {settings.APP_ENV} mode...")
    try:
        await init_db()
    except Exception as e:
        logger.warning(f"Database init warning (running in in-memory mode): {e}")
    yield
    logger.info(f"Shutting down {settings.APP_NAME}...")

app = FastAPI(
    title=settings.APP_NAME,
    version="1.0.0",
    description=(
        "FinSight AI: Generative AI Investment Intelligence & Stock Research Platform.\n\n"
        "**Regulatory Disclaimer:** FinSight AI is a research and demonstration platform. "
        "Information generated by the system does not constitute financial advice and "
        "should not be considered a recommendation to buy or sell securities."
    ),
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan
)

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Permits localhost and container cross-origin calls
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request ID & Latency Telemetry Middleware
@app.middleware("http")
async def add_process_time_and_request_id(request: Request, call_next):
    req_id = str(uuid.uuid4())
    request.state.request_id = req_id
    start_time = time.time()
    
    response = await call_next(request)
    
    process_time = (time.time() - start_time) * 1000.0
    response.headers["X-Request-ID"] = req_id
    response.headers["X-Process-Time-Ms"] = f"{process_time:.2f}"
    return response

# Global Exception Handler
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Unhandled error on {request.url.path}: {str(exc)}", exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error": "Internal Server Error",
            "detail": "An unexpected error occurred. Consult server telemetry logs.",
            "request_id": getattr(request.state, "request_id", "unknown")
        }
    )

# Root & Health Check Endpoints
@app.get("/health", tags=["Health"])
async def health_check():
    return {
        "status": "operational",
        "app_name": settings.APP_NAME,
        "version": "1.0.0",
        "demo_mode": settings.DEMO_MODE,
        "provider": settings.DEFAULT_LLM_PROVIDER,
        "disclaimer": "FinSight AI is a research and demonstration platform."
    }

@app.get("/", tags=["Health"])
async def root():
    return {
        "message": f"Welcome to {settings.APP_NAME} API Gateway",
        "documentation": "/docs",
        "health": "/health",
        "version": "v1"
    }

# Register V1 API Routers
api_v1 = settings.API_V1_STR
app.include_router(auth_router, prefix=f"{api_v1}/auth", tags=["Authentication"])
app.include_router(stocks_router, prefix=f"{api_v1}/stocks", tags=["Stocks & Market Data"])
app.include_router(analytics_router, prefix=f"{api_v1}/analytics", tags=["Quantitative Analytics"])
app.include_router(sentiment_router, prefix=f"{api_v1}/sentiment", tags=["Financial Sentiment"])
app.include_router(rag_router, prefix=f"{api_v1}/rag", tags=["LangChain RAG Knowledge System"])
app.include_router(documents_router, prefix=f"{api_v1}/documents", tags=["Document Intelligence"])
app.include_router(agents_router, prefix=f"{api_v1}/agents", tags=["AI Research Agents"])
app.include_router(chat_router, prefix=f"{api_v1}/chat", tags=["AI Research Assistant"])
app.include_router(portfolio_router, prefix=f"{api_v1}/portfolio", tags=["Portfolio Intelligence"])
app.include_router(ml_router, prefix=f"{api_v1}/ml", tags=["Machine Learning Stock Lab"])
app.include_router(multimodal_router, prefix=f"{api_v1}/multimodal", tags=["Multimodal Vision AI"])
app.include_router(voice_router, prefix=f"{api_v1}/voice", tags=["Voice AI Assistant"])
app.include_router(showcase_router, prefix=f"{api_v1}/showcase", tags=["Technology Showcase & Evaluation"])
app.include_router(workflows_router, prefix=f"{api_v1}/workflows", tags=["Autonomous Research Workflows"])
app.include_router(approvals_router, prefix=f"{api_v1}/approvals", tags=["Human Approvals"])
app.include_router(strategies_router, prefix=f"{api_v1}/strategies", tags=["Strategies & Shadow Trading"])
app.include_router(system_router, prefix=f"{api_v1}/system", tags=["System Diagnostics"])

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.app.main:app", host=settings.HOST, port=settings.PORT, reload=settings.DEBUG)
